name: Auto EAS OTA Update

on:
  push:
    branches:
      - develop

jobs:
  eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Run EAS Update
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas update \
            --branch production \
            --message "Update OTA" \
            --rollout-percentage=100 \
            --non-interactive
